[network]
name = "simnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000

[accounts.oracle1]  
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 10_000_000_000_000

[accounts.user1]
mnemonic = "board list obtain sugar park nerve fossil milk lift topic maze anger person innocent relief system melt echo twenty unusual dawn butter exercise craft"
balance = 1_000_000_000_000